services:
  db:
    image: postgres:16-alpine
    container_name: secureapp_db_prod
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-secureapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secureapp}
      POSTGRES_DB: ${POSTGRES_DB:-secureapp}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/10-init.sql:ro
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-secureapp}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - secureapp_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod #  Dockerfile de PROD
    container_name: secureapp_backend_prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-4000}
      HOST: 0.0.0.0
      HTTPS_ENABLED: ${HTTPS_ENABLED:-false}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-15m}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION:-7d}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_ORIGINS: ${FRONTEND_ORIGINS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@secureapp.com}
    ports:
      - "127.0.0.1:${BACKEND_PORT:-4000}:4000"
    networks:
      - secureapp_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # ⬅️ Dockerfile de PROD
    container_name: secureapp_frontend_prod
    restart: unless-stopped
    env_file:
      - backend/.env
    depends_on:
      backend:
        condition: service_started
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-8080}:80"
    networks:
      - secureapp_net

volumes:
  db_data:


networks:
  secureapp_net:
    driver: bridge
