services:
  db:
    image: postgres:16-alpine
    container_name: secureapp_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB required}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/10-init.sql:ro
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-secureapp}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - secureapp_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod #  Dockerfile de PROD
    container_name: secureapp_backend_prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:?BACKEND_PORT required}
      HOST: 0.0.0.0
      HTTPS_ENABLED: ${HTTPS_ENABLED:?HTTPS_ENABLED required}
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL required}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET required}
      JWT_EXPIRATION: ${JWT_EXPIRATION:?JWT_EXPIRATION required}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION:?REFRESH_EXPIRATION required}
      FRONTEND_URL: ${FRONTEND_URL:?FRONTEND_URL required}
      FRONTEND_ORIGINS: ${FRONTEND_ORIGINS:?FRONTEND_ORIGINS required}
      SMTP_HOST: ${SMTP_HOST:?SMTP_HOST required}
      SMTP_PORT: ${SMTP_PORT:?SMTP_PORT required}
      SMTP_USER: ${SMTP_USER:?SMTP_USER required}
      SMTP_PASS: ${SMTP_PASS:?SMTP_PASS required}
      ADMIN_EMAIL: ${ADMIN_EMAIL:?ADMIN_EMAIL required}
      ADMIN_LOGIN: ${ADMIN_LOGIN:?ADMIN_LOGIN required}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?ADMIN_PASSWORD required}
      ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME:?ADMIN_FIRST_NAME required}
      ADMIN_LAST_NAME: ${ADMIN_LAST_NAME:?ADMIN_LAST_NAME required}
      ADMIN_AVATAR_URL: ${ADMIN_AVATAR_URL:?ADMIN_AVATAR_URL required}
      ADMIN_PHONE: ${ADMIN_PHONE:?ADMIN_PHONE required}
    ports:
      - "127.0.0.1:${BACKEND_PORT:-4000}:4000"
    networks:
      - secureapp_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # ⬅️ Dockerfile de PROD
    container_name: secureapp_frontend_prod
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-8080}:80"
    networks:
      - secureapp_net

volumes:
  db_data:


networks:
  secureapp_net:
    driver: bridge
